# Site settings
title:          ellemaker
description:    "personal blog site"
baseurl:        ""
url:            "https://ellemaker.github.io/"

# Author
author:
  name:         ellemaker
  url:          https://ellemaker.github.io/
  email:        ellebarde@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:year-:month-:day/:title
paginate:       5
