# Site settings
title:          anbaks
description:    "Anbaks talks about latest technology from development to user end"
baseurl:        ""
url:            "https://anbaks.github.io/"

# Author
author:
  name:         ellemaker
  url:          https://anbaks.github.io/
  email:        anbaks2000@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:year-:month-:day/:title
paginate:       5
